name: 0.1-Create All
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}

jobs:
  terraform_apply:
    name: Terraform Apply All
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Apply All
      run: |
        cd ./1-build-remote-state
        terraform init
        terraform plan
        terraform apply -auto-approve