name: 4a-1 | Create | EC2 Setup
on: 
  workflow_dispatch
env:
  REGION: ${{ vars.REGIAO }}
  REMOTE_STATE_BUCKET: ${{ vars.REMOTE_STATE_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}  

jobs:
  check-out:
    name: "Create: EC2 Setup"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

  vpc-network:
    name: "VPC Network: Create"
    runs-on: ubuntu-latest
    needs: 
      - check-out
    if: ${{ true }}
    steps:
    - name: "VPC Network: Setup backend, run terraform init and apply."
      env:
        KEY_TF_STATE: "VPC Network/terraform.tfstate"
        LOCAL_FOLDER: "2-VPC Network"
      run: |
        chmod 755 ./generate_backend.sh && ./generate_backend.sh
        cd "./${{env.LOCAL_FOLDER}}"
        terraform init -backend-config=./backend.tfvars
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}"

  rds-database:
    name: "RDS Database: Create"
    runs-on: ubuntu-latest
    needs: 
      - vpc-network    
    steps:    
    - name: "RDS Database: Setup backend, run terraform init and apply."
      env:
        KEY_TF_STATE: "RDS Database/terraform.tfstate"
        LOCAL_FOLDER: "3b-RDS Database"
      run: |
        chmod 755 ./generate_backend.sh && ./generate_backend.sh
        cd "./${{env.LOCAL_FOLDER}}"
        terraform init -backend-config=./backend.tfvars
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}"

  ec2-setup:
    name: "EC2 Setup: Create"
    runs-on: ubuntu-latest
    needs: 
      - rds-database
    steps:           
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.AWS_DEV_CLI_ADMIN_SSH_PRIVATE_KEY }}
    - name: "EC2 Setup: Setup backend, run terraform init and apply."
      env:
        KEY_TF_STATE: "EC2 Setup/terraform.tfstate"
        LOCAL_FOLDER: "4a-EC2 Setup"
      run: |
        chmod 755 ./generate_backend.sh && ./generate_backend.sh
        cd "./${{env.LOCAL_FOLDER}}"
        terraform init -backend-config=./backend.tfvars
        terraform apply -auto-approve \
          -var "regiao=${{env.REGION}}" \
          -var "remote-state-bucket=${{env.REMOTE_STATE_BUCKET}}"